### ISSUE TITLE
Pulsating BrainStone doesnt do anything!

### ISSUE THREAD

**Issue by Luckie21** [BrainStone/brainstone#16]
Pulsating Brainstone use to give me stuff like nausea 3 and luck 4 but it just sits there and does nothing! this is the unstable kind to

**Comment by BrainStone** [comment]
Minecraft version, Mod version and Forge version?

**Comment by BrainStone** [comment]
Also were you wearing Brain Stone or Stable Pulsating Brain Stone Armor?
Because both protect you from the effects of it.

**Comment by BrainStone** [comment]
I did my testing and can confirm that the Pulsating Brain Stone is working. It only does not work when wearing either full Brain Stone or Stable Pulsating Brain Stone Armor which is intended.

So I'm going to close it. If you in fact did have another issue just add a commetn describing it in more detail.
