### ISSUE TITLE
[1.10.2-4.4.6-beta] Crash report

### ISSUE THREAD

**Issue by The-Fireplace** [BrainStone/brainstone#22]
#### What happens:
The game crashes on launch

#### What you expected to happen:
No crash

#### Steps to reproduce:

1. Launch the game

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- BrainStoneMod: 4.4.6-beta
- Forge: 12.18.3.2202
- Other related mods:

#### Your most recent log or stack trace file where the issue was present: 
http://paste.ubuntu.com/23824115/

**Comment by BrainStone** [comment]
That's very strange. When I run it without any other mods it works fine and with other modpacks (like Skyfactory 3) it's working too.

I suspect another mod is adding back the old CoFH API but without the  `cofh.api.energy.IEnergyContainerItem` class. This causes the mod to crash.  
Could you check the jars of the mod for the package `cofh.api` and tell me which mods do have it?  
This should make debugging a lot easier!

**Comment by The-Fireplace** [comment]
Sure.

On Jan 18, 2017 2:59 PM, "BrainStone" <notifications@github.com> wrote:

That's very strange. When I run it without any other mods it works fine and
with other modpacks (like Skyfactory 3) it's working too.

I suspect another mod is adding back the old CoFH API but without the
cofh.api.energy.IEnergyContainerItem class. This causes the mod to crash.
Could you check the jars of the mod for the package cofh.api and tell me
which mods do have it?
This should make debugging a lot easier!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BrainStone/brainstone/issues/22#issuecomment-273600020>,
or mute the thread

**Comment by The-Fireplace** [comment]
Here, Railcraft is loaded, and it has the API. And that class is present.
![image](https://cloud.githubusercontent.com/assets/5914284/22110058/fb0fcb52-de1f-11e6-97df-ea9ff82565db.png)
