### ISSUE TITLE
BrainStone Life Capacitor recipe doesn't show in JEI when clicking the drained item.

### ISSUE THREAD

**Issue by The-Fireplace** [BrainStone/brainstone#24]
#### Issue Description:
The BrainStone Life Capacitor recipe doesn't show up in JEI when checking the drained version of the item.

#### What happens:
When checking the recipe, it just shows the upgrades

#### What you expected to happen:
It gives me the recipe to make the life capacitor

#### Steps to reproduce:

1. Open JEI
2. Check life capacitor recipe

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- BrainStoneMod: 4.4.35-beta
- Forge: 12.18.3.2281
- Other related mods: JEI 3.14.7.419

**Comment by BrainStone** [comment]
Fixed by 2c3b23698dadaea5b2ff93780bc2bf21c1b763f8
