### ISSUE TITLE
[1.12] Tinkers Integration Broken

### ISSUE THREAD

**Issue by BrisingrAerowing** [BrainStone/brainstone#25]
#### Issue Description:
Startup crash with Tinkers integration

#### What happens:
Crash with recent tinkers

#### What you expected to happen:
Game loads

#### Steps to reproduce:

1. Get recent TConstruct and Brain Stone
2. Try to run game
3. ...
4. Crash!

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- BrainStoneMod: 4.6.5
- Forge: 2469
- Other related mods: TConstruct - 2.7.2.19 (and later)

#### Your most recent log or stack trace file where the issue was present: 

[Crash Log](https://gist.github.com/BrisingrAerowing/6078ed54a21d670d98cea6dde9a291ee)

**Comment by BrainStone** [comment]
Thanks for reporting. The fix should be available on Curse within 30 minutes.
