### ISSUE TITLE
Brain stone Life Capacitor shows up in all creative tabs.

### ISSUE THREAD

**Issue by BrisingrAerowing** [BrainStone/brainstone#26]
#### Issue Description:
As per title.

#### What happens:

BSLC in all creative tabs

#### What you expected to happen:

BSLC only in its creative tab.

#### Steps to reproduce:

1. Open creative menu
2. Browse through tabs

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- BrainStoneMod: 4.6.8
- Forge: 2469
- Other related mods: N/A

#### Your most recent log or stack trace file where the issue was present: 
N/A

#### Notes

The issue here is that a new method named 'isInCreativeTab' needs to be called within any 'getSubItems' methods for any item that has that method.

**Comment by BrainStone** [comment]
Ok. Thanks for the hint. I'll soon have a look.
