### ISSUE TITLE
Not compatible w/ Tinkers Construct

### ISSUE THREAD

**Issue by mahilo3550** [BrainStone/brainstone#27]
#### Issue Description:
Brain Stone Block/Ore & Stable Pulsating Brain Stone Block/Ore do not work with Tinkers Construct even though config file says it's enabled.

#### What happens:
Nothing

#### What you expected to happen:
Be able to use Brain Stone/Pulsating Brain Stone/Stable Pulsating Brain Stone as a material in Tinkers Construct

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- BrainStoneMod: 4.6.30beta
- Forge: 14.21.1.2443
- Other related mods: Tinkers Construct

#### Your most recent log or stack trace file where the issue was present: 

[pastebin/gist/etc link here]

```
[Or stack trace here (Remove this if you don't put anything here!)]
```

**Comment by BrainStone** [comment]
You can't smelt the blocks. You'll have to create the parts in a part builder.
