### ISSUE TITLE
Just Enough Resources not usable w/ Brain Stone Mod

### ISSUE THREAD

**Issue by mahilo3550** [BrainStone/brainstone#28]
#### What happens:

Crash on start-up stating Brain Stone Mod is the Issue

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- BrainStoneMod:
- Forge:
- Other related mods:

#### Your most recent log or stack trace file where the issue was present: 

[pastebin/gist/etc link here]

```
[Or stack trace here (Remove this if you don't put anything here!)]
```

**Comment by BrainStone** [comment]
@mahilo3550 I need the version numbers.

**Comment by The-Fireplace** [comment]
@mahilo3550 the log would also be very useful. The template is there for a reason.

**Comment by BrainStone** [comment]
Closing because stale
