### ISSUE TITLE
crash on startup 

### ISSUE THREAD

**Issue by IchigoGames** [BrainStone/brainstone#29]
#### Issue Description:
I was testing some stuff for updating my pack to 1.12.2 and had a crash on startup from brainstone mod i think it's incompatible with another mod.

#### What happens:
it crashed on start up

#### What you expected to happen:
not crash

#### Steps to reproduce:

1. added BrainStoneMod to a 1.12.2 test pack
2. added all the other mods from Beyond The New Frontier
3. clicked update on all mods that had updates
4. clicked lunch game,
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- BrainStoneMod: BrainStoneMod-1.12-4.6.30-beta
- Forge: 2491
- Other related mods: theres two Meany to list here

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/JfytfQHy

**Comment by BrainStone** [comment]
Fixed by now
