### ISSUE TITLE
Missing/Broken Texture

### ISSUE THREAD

**Issue by Fortist** [BrainStone/brainstone#30]
For 1.12.2, the stable pulsating block is missing its texture.
I checked the assets folder and Im not seeing anything wrong with the naming conventions.

"stable_pulsating_brain_stone_ctm.png" and "stable_pulsating_brain_stone.png" with the meta files along with it, are there.

**Comment by BrainStone** [comment]
Do you have CTM installed?

**Comment by BrainStone** [comment]
Closing because stale
