### ISSUE TITLE
Forestry integration needs updating

### ISSUE THREAD

**Issue by BrisingrAerowing** [BrainStone/brainstone#31]
#### Issue Description:
Crash with Forestry due to a major change to the plugin system (now called modules)

#### What happens:
Crash

#### What you expected to happen:
Loaded successfully

#### Steps to reproduce:

1. Load with recent Forestry
2. ...?
3. ~~Profit!~~ Crash!
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- BrainStoneMod: 4.6.30-beta
- Forge: 2537
- Other related mods: Forestry 5.7.0.210

#### Your most recent log or stack trace file where the issue was present: 
[Crash Log](https://gist.github.com/BrisingrAerowing/e0619bae6b3b697321505ebe4d4f45da)

**Comment by BrainStone** [comment]
Pretty sure that is implemented by now. If not, just reopen the issue.
