### ISSUE TITLE
Crash when updating to Immersive Engineering - 0.12 - 78

### ISSUE THREAD

**Issue by karikusa** [BrainStone/brainstone#32]
#### What happens:
Immersive Engineering - Updated from 0.12 - 77 to 78, somehow BrainStoneMod got an error and crashed at startup.
I tried thinking that Optifine was the cause, but when I pulled out BrainStone I found that IE 78 can be started normally even with IE 78 in.
Perhaps this is probably a BrainStoneMOD error.

#### What you expected to happen:
I thought that I could normally start as much as I had breakfast.

#### Steps to reproduce:

1: Update IE to 78 keeping BrainStone in
2: I could not boot and crashed
3: I pulled out of BrainStone and it was able to run even in IE78  ;D

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- BrainStoneMod:1.12-4.6.30-beta
- Forge:2624&2615
- Other related mods:LiteLoader

#### Your most recent log or stack trace file where the issue was present: 
[crash-2018-03-03_12.22.50-client.txt](https://github.com/BrainStone/brainstone/files/1777076/crash-2018-03-03_12.22.50-client.txt)

####PS: Since I will not go through to extract BrainStone, I will go with IE 77 until the error is fixed XD

**Comment by The-Fireplace** [comment]
Looks like IE changed something that broke our integration. Revert to the
previous build of IE for now, until we can get a fix out.

**Comment by BrainStone** [comment]
Does this still happen?
