### ISSUE TITLE
brainstonemod.com has changed ownership

### ISSUE THREAD

**Issue by cjm721** [BrainStone/brainstone#33]
brainstonemod.com is now owned by a parking company that known for malicious links. Would suggest disabling the update check until you get a new website up and running.

Since its running through forge's update mechanism it can't really do anything harmful, but if they noticed they could format the response to show any message they want to the user.

**Comment by BrainStone** [comment]
Current versions have the check removed already.

But thank you for pointing it out :)

**Comment by cjm721** [comment]
Pulling version 1.12.2-4.7.20-beta off curse it still has the updateJson set in the mod annotation. Isn't that what is triggering the call?
