### ISSUE TITLE
Crash with MysticalAgriculture

### ISSUE THREAD

**Issue by IchigoGames** [BrainStone/brainstone#34]
#### Issue Description:
Added Brainstone mod to modpack and crashed looks a compatibility issue with Brainstone  and MysticalAgriculture

#### What happens:
it crashed  to desktop

#### What you expected to happen:
Not to crash

#### Steps to reproduce:

1. add brainstone
2. add MysticalAgriculture
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- BrainStoneMod:BrainStoneMod-1.12.2-4.6.54
- Forge:2847
- Other related mods: MysticalAgriculture-1.12.2-1.7.5

#### Your most recent log or stack trace file where the issue was present: 

[pastebin/gist/etc link here]

https://pastebin.com/093RDwAP
https://www.dropbox.com/s/qin9gavccee2bst/latest.log?dl=0

**Comment by BrainStone** [comment]
I see. This bug has been fixed in the latest dev version. I'll release it to Curse.

**Comment by BrainStone** [comment]
https://www.curseforge.com/minecraft/mc-mods/brain-stone-mod/files/2830173
