### ISSUE TITLE
Crashed when added with enderio

### ISSUE THREAD

**Issue by IchigoGames** [BrainStone/brainstone#35]
#### Issue Description:
I Hate to be back so soon but after i updated the mod and put it in pack it crashed this time
from enderio.

#### What happens:
Crash when added

#### What you expected to happen:
not crashing

#### Steps to reproduce:

1. added BrainStoneMod-1.12.2-4.7.48-beta
2. with EnderIO-1.12.2-5.1.52
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
-  BrainStoneMod-1.12.2-4.7.48-beta
- Forge:2847
- Other related mods:EnderIO-1.12.2-5.1.52

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/e2vGhPpg
https://www.dropbox.com/s/0jh5g4gmf99jte6/latest.log?dl=0

**Comment by BrainStone** [comment]
Gad damn it xD
Why do they always have to change their stuff so much...
